#!/bin/bash

# a little setup
BUILD_OUTPUT=~/android-aokp/out/target/product/cooper
ADDONS_DIR=./DV.addons
TIMESTAMP=`date +"%Y%m%d-%H%M"`
ZIPFILENAME=aokp-DarkVision-$TIMESTAMP-DEV.zip

# clean previous builds
rm -rf ./system
rm -f ./boot.img
cp -r $BUILD_OUTPUT/system .
cp $BUILD_OUTPUT/boot.img .

# get rid of symlinks, but save them to a text file
find ./system/bin -maxdepth 1 -type l -exec ls -lh {} \; > symlinks.txt
find ./system/bin -maxdepth 1 -type l -exec rm -f {} \;
find ./system/xbin -maxdepth 1 -type l -exec ls -lh {} \; >> symlinks.txt
find ./system/xbin -maxdepth 1 -type l -exec rm -f {} \;
find ./system/fonts -maxdepth 1 -type l -exec ls -lh {} \; >> symlinks.txt
find ./system/fonts -maxdepth 1 -type l -exec rm -f {} \;

# put some nice add-ons
cp -r $ADDONS_DIR/* ./system

# ok, make a package
cp aokp-DarkVision.template.zip $ZIPFILENAME
zip -r $ZIPFILENAME ./system
zip $ZIPFILENAME boot.img

